openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: These are the APIs of Blogging Platform

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /:
    get:
      tags:
        - Home
      description: Home
      responses:
        '200':
          description: Home Page
        '401':
          description: Unauthorized
  
  /user/:
    get:
      tags:
        - User API
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /user/login:
    post:
      tags:
        - User API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Email:
                  type: string
                Password:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /user/register:
    post:
      tags:
        - User API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Name:
                  type: string
                Email:
                  type: string
                Password:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request


  /post/create:
    post:
      tags:
        - Post API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                author:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /post/:
    get:
      tags:
        - Post API
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /post/getpost/{id}:
    get:
      tags:
        - Post API
      parameters:
      - in: path
        name: id
        required: true
        description: ID of the blog post to retrieve.
        schema:
          type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request


  /post/update/{id}:
    patch:
      tags:
        - Post API
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the blog post to update.
          schema:
            type: string
        - in: body
          name: requestBody
          required: true
          description: Updated post data.
          schema:
            type: object
            properties:
              title:
                type: string
              content:
                type: string
              
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request



  /post/delete/{id}:
    delete:
      tags:
        - Post API
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the blog post to delete.
          schema:
            type: string
      responses:
        '200':
          description: Success
        '404':
          description: Blog post not found
        '500':
          description: Internal server error